development: &development
    access_key_id: <%= Rails.application.secrets.aws_access_key_id %>
    secret_access_key: <%= Rails.application.secrets.aws_secret_access_key %>
    s3_endpoint:         "localhost"
    s3_port:             10001
    s3_force_path_style: true
    use_ssl:             false

test: *development
    
production: &production
  access_key_id: <%= Rails.application.secrets.aws_access_key_id %>
  secret_access_key: <%= Rails.application.secrets.aws_secret_access_key %>

staging: *production