development:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
    timeout: 5000

production:
    adapter: mysql2
    reconnect: false
    pool: 5
    host: <%= Rails.application.secrets.db_host %>
    port: <%= Rails.application.secrets.db_port %>
    database: <%= Rails.application.secrets.db_database %>
    username: <%= Rails.application.secrets.db_username %>
    password: <%= Rails.application.secrets.db_password %>
