development:
    hash_data: ":class/:attachment/:id/:updated_at"
    hash_secret: <%= Rails.application.secrets.paperclip_secret%>
    path: "/:class/:uuid/:hash_:style.:extension"

production:
    hash_data: ":class/:attachment/:id/:updated_at"
    hash_secret: <%= Rails.application.secrets.paperclip_secret%>
    path: "/:class/:uuid/:hash_:style.:extension"
