development: &development
    :storage:       :s3
    bucket:        <%= Rails.application.secrets.aws_s3_bucket %>
    s3_host_name:  "localhost"
    url:           ":s3_alias_url"
    path:          ":class/:attachment/:id_partition/:filename_:style.:extension"
    s3_host_alias: "localhost:10001/<%= Rails.application.secrets.aws_s3_bucket %>"

test: *development

production: &production
    storage: :s3
    bucket:  <%= Rails.application.secrets.aws_s3_bucket %>
    url:     ":s3_domain_url"
    path:    ":class/:attachment/:id_partition/:filename_:style.:extension"

staging: *production
