# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# Esportes - begin
unless Esporte.exists?
  # Modalidades Skate
  Esporte.create(nome: "Street", categoria: "skate")
  Esporte.create(nome: "Longboard", categoria: "skate")
  Esporte.create(nome: "Downhill", categoria: "skate")
  Esporte.create(nome: "Slalom", categoria: "skate")
  Esporte.create(nome: "Freestyle", categoria: "skate")
  Esporte.create(nome: "Vertical", categoria: "skate")
  Esporte.create(nome: "Mountainboard", categoria: "skate")
  # Modalidades Patins
  Esporte.create(nome: "Street", categoria: "patins")
  Esporte.create(nome: "Fitness", categoria: "patins")
  Esporte.create(nome: "Slalom", categoria: "patins")
  Esporte.create(nome: "Freestyle", categoria: "patins")
  Esporte.create(nome: "Vertical", categoria: "patins")
  Esporte.create(nome: "Speed", categoria: "patins")
  Esporte.create(nome: "Downhill", categoria: "patins")
  Esporte.create(nome: "Hockey", categoria: "patins")
  Esporte.create(nome: "Roller Derby", categoria: "patins")
  Esporte.create(nome: "Artistic", categoria: "patins")
  # Modalidade bike
  Esporte.create(nome: "BMX", categoria: "bike")
  Esporte.create(nome: "Drift Trike", categoria: "bike")
  Esporte.create(nome: "Cross-Country", categoria: "bike")
  Esporte.create(nome: "Downhill", categoria: "bike")
  Esporte.create(nome: "Four-Cross", categoria: "bike")
  Esporte.create(nome: "Marathon", categoria: "bike")
  Esporte.create(nome: "Trial", categoria: "bike")
  Esporte.create(nome: "Enduro", categoria: "bike")
  Esporte.create(nome: "Freeride", categoria: "bike")
end
# Esportes - end

# Contries - begin #
unless Country.exists?
  Country.create(iso: "AD", name: "Andorra")
  Country.create(iso: "AE", name: "United Arab Emirates")
  Country.create(iso: "AF", name: "Afghanistan")
  Country.create(iso: "AG", name: "Antigua and Barbuda")
  Country.create(iso: "AI", name: "Anguilla")
  Country.create(iso: "AL", name: "Albania")
  Country.create(iso: "AM", name: "Armenia")
  Country.create(iso: "AO", name: "Angola")
  Country.create(iso: "AQ", name: "Antarctica")
  Country.create(iso: "AR", name: "Argentina")
  Country.create(iso: "AS", name: "American Samoa")
  Country.create(iso: "AT", name: "Austria")
  Country.create(iso: "AU", name: "Australia")
  Country.create(iso: "AW", name: "Aruba")
  Country.create(iso: "AX", name: "Aland Islands")
  Country.create(iso: "AZ", name: "Azerbaijan")
  Country.create(iso: "BA", name: "Bosnia and Herzegovina")
  Country.create(iso: "BB", name: "Barbados")
  Country.create(iso: "BD", name: "Bangladesh")
  Country.create(iso: "BE", name: "Belgium")
  Country.create(iso: "BF", name: "Burkina Faso")
  Country.create(iso: "BG", name: "Bulgaria")
  Country.create(iso: "BH", name: "Bahrain")
  Country.create(iso: "BI", name: "Burundi")
  Country.create(iso: "BJ", name: "Benin")
  Country.create(iso: "BL", name: "Saint Barthelemy")
  Country.create(iso: "BM", name: "Bermuda")
  Country.create(iso: "BN", name: "Brunei")
  Country.create(iso: "BO", name: "Bolivia")
  Country.create(iso: "BQ", name: "Bonaire, Saint Eustatius and Saba ")
  Country.create(iso: "BR", name: "Brazil")
  Country.create(iso: "BS", name: "Bahamas")
  Country.create(iso: "BT", name: "Bhutan")
  Country.create(iso: "BV", name: "Bouvet Island")
  Country.create(iso: "BW", name: "Botswana")
  Country.create(iso: "BY", name: "Belarus")
  Country.create(iso: "BZ", name: "Belize")
  Country.create(iso: "CA", name: "Canada")
  Country.create(iso: "CC", name: "Cocos Islands")
  Country.create(iso: "CD", name: "Democratic Republic of the Congo")
  Country.create(iso: "CF", name: "Central African Republic")
  Country.create(iso: "CG", name: "Republic of the Congo")
  Country.create(iso: "CH", name: "Switzerland")
  Country.create(iso: "CI", name: "Ivory Coast")
  Country.create(iso: "CK", name: "Cook Islands")
  Country.create(iso: "CL", name: "Chile")
  Country.create(iso: "CM", name: "Cameroon")
  Country.create(iso: "CN", name: "China")
  Country.create(iso: "CO", name: "Colombia")
  Country.create(iso: "CR", name: "Costa Rica")
  Country.create(iso: "CU", name: "Cuba")
  Country.create(iso: "CV", name: "Cape Verde")
  Country.create(iso: "CW", name: "Curacao")
  Country.create(iso: "CX", name: "Christmas Island")
  Country.create(iso: "CY", name: "Cyprus")
  Country.create(iso: "CZ", name: "Czech Republic")
  Country.create(iso: "DE", name: "Germany")
  Country.create(iso: "DJ", name: "Djibouti")
  Country.create(iso: "DK", name: "Denmark")
  Country.create(iso: "DM", name: "Dominica")
  Country.create(iso: "DO", name: "Dominican Republic")
  Country.create(iso: "DZ", name: "Algeria")
  Country.create(iso: "EC", name: "Ecuador")
  Country.create(iso: "EE", name: "Estonia")
  Country.create(iso: "EG", name: "Egypt")
  Country.create(iso: "EH", name: "Western Sahara")
  Country.create(iso: "ER", name: "Eritrea")
  Country.create(iso: "ES", name: "Spain")
  Country.create(iso: "ET", name: "Ethiopia")
  Country.create(iso: "FI", name: "Finland")
  Country.create(iso: "FJ", name: "Fiji")
  Country.create(iso: "FK", name: "Falkland Islands")
  Country.create(iso: "FM", name: "Micronesia")
  Country.create(iso: "FO", name: "Faroe Islands")
  Country.create(iso: "FR", name: "France")
  Country.create(iso: "GA", name: "Gabon")
  Country.create(iso: "GB", name: "United Kingdom")
  Country.create(iso: "GD", name: "Grenada")
  Country.create(iso: "GE", name: "Georgia")
  Country.create(iso: "GF", name: "French Guiana")
  Country.create(iso: "GG", name: "Guernsey")
  Country.create(iso: "GH", name: "Ghana")
  Country.create(iso: "GI", name: "Gibraltar")
  Country.create(iso: "GL", name: "Greenland")
  Country.create(iso: "GM", name: "Gambia")
  Country.create(iso: "GN", name: "Guinea")
  Country.create(iso: "GP", name: "Guadeloupe")
  Country.create(iso: "GQ", name: "Equatorial Guinea")
  Country.create(iso: "GR", name: "Greece")
  Country.create(iso: "GS", name: "South Georgia and the South Sandwich Islands")
  Country.create(iso: "GT", name: "Guatemala")
  Country.create(iso: "GU", name: "Guam")
  Country.create(iso: "GW", name: "Guinea-Bissau")
  Country.create(iso: "GY", name: "Guyana")
  Country.create(iso: "HK", name: "Hong Kong")
  Country.create(iso: "HM", name: "Heard Island and McDonald Islands")
  Country.create(iso: "HN", name: "Honduras")
  Country.create(iso: "HR", name: "Croatia")
  Country.create(iso: "HT", name: "Haiti")
  Country.create(iso: "HU", name: "Hungary")
  Country.create(iso: "ID", name: "Indonesia")
  Country.create(iso: "IE", name: "Ireland")
  Country.create(iso: "IL", name: "Israel")
  Country.create(iso: "IM", name: "Isle of Man")
  Country.create(iso: "IN", name: "India")
  Country.create(iso: "IO", name: "British Indian Ocean Territory")
  Country.create(iso: "IQ", name: "Iraq")
  Country.create(iso: "IR", name: "Iran")
  Country.create(iso: "IS", name: "Iceland")
  Country.create(iso: "IT", name: "Italy")
  Country.create(iso: "JE", name: "Jersey")
  Country.create(iso: "JM", name: "Jamaica")
  Country.create(iso: "JO", name: "Jordan")
  Country.create(iso: "JP", name: "Japan")
  Country.create(iso: "KE", name: "Kenya")
  Country.create(iso: "KG", name: "Kyrgyzstan")
  Country.create(iso: "KH", name: "Cambodia")
  Country.create(iso: "KI", name: "Kiribati")
  Country.create(iso: "KM", name: "Comoros")
  Country.create(iso: "KN", name: "Saint Kitts and Nevis")
  Country.create(iso: "KP", name: "North Korea")
  Country.create(iso: "KR", name: "South Korea")
  Country.create(iso: "XK", name: "Kosovo")
  Country.create(iso: "KW", name: "Kuwait")
  Country.create(iso: "KY", name: "Cayman Islands")
  Country.create(iso: "KZ", name: "Kazakhstan")
  Country.create(iso: "LA", name: "Laos")
  Country.create(iso: "LB", name: "Lebanon")
  Country.create(iso: "LC", name: "Saint Lucia")
  Country.create(iso: "LI", name: "Liechtenstein")
  Country.create(iso: "LK", name: "Sri Lanka")
  Country.create(iso: "LR", name: "Liberia")
  Country.create(iso: "LS", name: "Lesotho")
  Country.create(iso: "LT", name: "Lithuania")
  Country.create(iso: "LU", name: "Luxembourg")
  Country.create(iso: "LV", name: "Latvia")
  Country.create(iso: "LY", name: "Libya")
  Country.create(iso: "MA", name: "Morocco")
  Country.create(iso: "MC", name: "Monaco")
  Country.create(iso: "MD", name: "Moldova")
  Country.create(iso: "ME", name: "Montenegro")
  Country.create(iso: "MF", name: "Saint Martin")
  Country.create(iso: "MG", name: "Madagascar")
  Country.create(iso: "MH", name: "Marshall Islands")
  Country.create(iso: "MK", name: "Macedonia")
  Country.create(iso: "ML", name: "Mali")
  Country.create(iso: "MM", name: "Myanmar")
  Country.create(iso: "MN", name: "Mongolia")
  Country.create(iso: "MO", name: "Macao")
  Country.create(iso: "MP", name: "Northern Mariana Islands")
  Country.create(iso: "MQ", name: "Martinique")
  Country.create(iso: "MR", name: "Mauritania")
  Country.create(iso: "MS", name: "Montserrat")
  Country.create(iso: "MT", name: "Malta")
  Country.create(iso: "MU", name: "Mauritius")
  Country.create(iso: "MV", name: "Maldives")
  Country.create(iso: "MW", name: "Malawi")
  Country.create(iso: "MX", name: "Mexico")
  Country.create(iso: "MY", name: "Malaysia")
  Country.create(iso: "MZ", name: "Mozambique")
  Country.create(iso: "NA", name: "Namibia")
  Country.create(iso: "NC", name: "New Caledonia")
  Country.create(iso: "NE", name: "Niger")
  Country.create(iso: "NF", name: "Norfolk Island")
  Country.create(iso: "NG", name: "Nigeria")
  Country.create(iso: "NI", name: "Nicaragua")
  Country.create(iso: "NL", name: "Netherlands")
  Country.create(iso: "NO", name: "Norway")
  Country.create(iso: "NP", name: "Nepal")
  Country.create(iso: "NR", name: "Nauru")
  Country.create(iso: "NU", name: "Niue")
  Country.create(iso: "NZ", name: "New Zealand")
  Country.create(iso: "OM", name: "Oman")
  Country.create(iso: "PA", name: "Panama")
  Country.create(iso: "PE", name: "Peru")
  Country.create(iso: "PF", name: "French Polynesia")
  Country.create(iso: "PG", name: "Papua New Guinea")
  Country.create(iso: "PH", name: "Philippines")
  Country.create(iso: "PK", name: "Pakistan")
  Country.create(iso: "PL", name: "Poland")
  Country.create(iso: "PM", name: "Saint Pierre and Miquelon")
  Country.create(iso: "PN", name: "Pitcairn")
  Country.create(iso: "PR", name: "Puerto Rico")
  Country.create(iso: "PS", name: "Palestinian Territory")
  Country.create(iso: "PT", name: "Portugal")
  Country.create(iso: "PW", name: "Palau")
  Country.create(iso: "PY", name: "Paraguay")
  Country.create(iso: "QA", name: "Qatar")
  Country.create(iso: "RE", name: "Reunion")
  Country.create(iso: "RO", name: "Romania")
  Country.create(iso: "RS", name: "Serbia")
  Country.create(iso: "RU", name: "Russia")
  Country.create(iso: "RW", name: "Rwanda")
  Country.create(iso: "SA", name: "Saudi Arabia")
  Country.create(iso: "SB", name: "Solomon Islands")
  Country.create(iso: "SC", name: "Seychelles")
  Country.create(iso: "SD", name: "Sudan")
  Country.create(iso: "SS", name: "South Sudan")
  Country.create(iso: "SE", name: "Sweden")
  Country.create(iso: "SG", name: "Singapore")
  Country.create(iso: "SH", name: "Saint Helena")
  Country.create(iso: "SI", name: "Slovenia")
  Country.create(iso: "SJ", name: "Svalbard and Jan Mayen")
  Country.create(iso: "SK", name: "Slovakia")
  Country.create(iso: "SL", name: "Sierra Leone")
  Country.create(iso: "SM", name: "San Marino")
  Country.create(iso: "SN", name: "Senegal")
  Country.create(iso: "SO", name: "Somalia")
  Country.create(iso: "SR", name: "Suriname")
  Country.create(iso: "ST", name: "Sao Tome and Principe")
  Country.create(iso: "SV", name: "El Salvador")
  Country.create(iso: "SX", name: "Sint Maarten")
  Country.create(iso: "SY", name: "Syria")
  Country.create(iso: "SZ", name: "Swaziland")
  Country.create(iso: "TC", name: "Turks and Caicos Islands")
  Country.create(iso: "TD", name: "Chad")
  Country.create(iso: "TF", name: "French Southern Territories")
  Country.create(iso: "TG", name: "Togo")
  Country.create(iso: "TH", name: "Thailand")
  Country.create(iso: "TJ", name: "Tajikistan")
  Country.create(iso: "TK", name: "Tokelau")
  Country.create(iso: "TL", name: "East Timor")
  Country.create(iso: "TM", name: "Turkmenistan")
  Country.create(iso: "TN", name: "Tunisia")
  Country.create(iso: "TO", name: "Tonga")
  Country.create(iso: "TR", name: "Turkey")
  Country.create(iso: "TT", name: "Trinidad and Tobago")
  Country.create(iso: "TV", name: "Tuvalu")
  Country.create(iso: "TW", name: "Taiwan")
  Country.create(iso: "TZ", name: "Tanzania")
  Country.create(iso: "UA", name: "Ukraine")
  Country.create(iso: "UG", name: "Uganda")
  Country.create(iso: "UM", name: "United States Minor Outlying Islands")
  Country.create(iso: "US", name: "United States")
  Country.create(iso: "UY", name: "Uruguay")
  Country.create(iso: "UZ", name: "Uzbekistan")
  Country.create(iso: "VA", name: "Vatican")
  Country.create(iso: "VC", name: "Saint Vincent and the Grenadines")
  Country.create(iso: "VE", name: "Venezuela")
  Country.create(iso: "VG", name: "British Virgin Islands")
  Country.create(iso: "VI", name: "U.S. Virgin Islands")
  Country.create(iso: "VN", name: "Vietnam")
  Country.create(iso: "VU", name: "Vanuatu")
  Country.create(iso: "WF", name: "Wallis and Futuna")
  Country.create(iso: "WS", name: "Samoa")
  Country.create(iso: "YE", name: "Yemen")
  Country.create(iso: "YT", name: "Mayotte")
  Country.create(iso: "ZA", name: "South Africa")
  Country.create(iso: "ZM", name: "Zambia")
  Country.create(iso: "ZW", name: "Zimbabwe")
  Country.create(iso: "CS", name: "Serbia and Montenegro")
  Country.create(iso: "AN", name: "Netherlands Antilles")
end
# Contries - end #

# Estados - begin
unless Estado.exists?
  c_br = Country.find_by_iso('BR');
  Estado.create(rg: "AC", nome: "Acre", country: c_br)
  Estado.create(rg: "AL", nome: "Alagoas", country: c_br)
  Estado.create(rg: "AP", nome: "Amapa", country: c_br)
  Estado.create(rg: "AM", nome: "Amazonas", country: c_br)
  Estado.create(rg: "BA", nome: "Bahia", country: c_br)
  Estado.create(rg: "CE", nome: "Ceara", country: c_br)
  Estado.create(rg: "DF", nome: "Distrito Federal", country: c_br)
  Estado.create(rg: "ES", nome: "Espírito Santo", country: c_br)
  Estado.create(rg: "GO", nome: "Goias", country: c_br)
  Estado.create(rg: "MA", nome: "Maranhão", country: c_br)
  Estado.create(rg: "MG", nome: "Minas Gerais", country: c_br)
  Estado.create(rg: "MT", nome: "Mato Grosso", country: c_br)
  Estado.create(rg: "MS", nome: "Mato Grosso do Sul", country: c_br)
  Estado.create(rg: "PA", nome: "Pará", country: c_br)
  Estado.create(rg: "PB", nome: "Paraíba", country: c_br)
  Estado.create(rg: "PR", nome: "Paraná", country: c_br)
  Estado.create(rg: "PE", nome: "Pernambuco", country: c_br)
  Estado.create(rg: "PI", nome: "Piauí", country: c_br)
  Estado.create(rg: "RJ", nome: "Rio de Janeiro", country: c_br)
  Estado.create(rg: "RN", nome: "Rio Grande do Norte", country: c_br)
  Estado.create(rg: "RS", nome: "Rio Grande do Sul", country: c_br)
  Estado.create(rg: "RR", nome: "Roraima", country: c_br)
  Estado.create(rg: "RO", nome: "Rondônia", country: c_br)
  Estado.create(rg: "SC", nome: "Santa Catarina", country: c_br)
  Estado.create(rg: "SE", nome: "Sergipe", country: c_br)
  Estado.create(rg: "SP", nome: "São Paulo", country: c_br)
  Estado.create(rg: "TO", nome: "Tocantins", country: c_br)
end
# Estados - end